# travis.yml for R projects
language: r

sudo: false
warnings_are_errors: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::coveralls()'
  - r: oldrel
  - r: 3.4
  - r: 3.3
  - r: 3.2
  - r: 3.1
  - r: 3.0

